# Preprocessing parameters
file_list: ['lfw.tgz','lfw-names.txt','training.txt','validation.txt','test.txt','labels.json']
dataset_name: 'lfw'
url_dataset: 'http://vis-www.cs.umass.edu/lfw/lfw.tgz'
url_metadata: 'http://vis-www.cs.umass.edu/lfw/lfw-names.txt'

# Parameters that may affect training
batch_size: 8
learning_rate: 0.001
max_steps: 3000
distance_threshold: 1.242

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_lfw: 'dataset\lfw'
labels_json: 'labels.json'
model_dir: 'checkpoints'

# Data configuration
shuffle: True
shuffle_buffer: 4
image_shape: [250,250]

# Logging and summaries 
eval_steps: 10
keep_checkpoint_max: 3
log_frequency: 20
save_checkpoints_steps: 20
save_summary_steps: 20
start_delay_secs: 10