# Parameters that may affect training
batch_size: 9
learning_rate: 0.001
max_steps: 1500

# Directories for dataset and checkpoints
data_dir: 'dataset'
data_dir_lfw: 'dataset\lfw_data'
labels_json: 'labels.json'
model_dir: 'checkpoints'

# Data configuration
shuffle: True
shuffle_buffer: 4
image_shape: [250,250]

# Logging and summaries 
eval_steps: 10
keep_checkpoint_max: 3
log_frequency: 20
save_checkpoints_steps: 20
save_summary_steps: 20
start_delay_secs: 10